/* 
 * JdbCaesar
 * Copyright © 2020 Anand Beh <https://www.arim.space>
 * 
 * JdbCaesar is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * 
 * JdbCaesar is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU Lesser General Public License for more details.
 * 
 * You should have received a copy of the GNU Lesser General Public License
 * along with JdbCaesar. If not, see <https://www.gnu.org/licenses/>
 * and navigate to version 3 of the GNU Lesser General Public License.
 */
package space.arim.jdbcaesar.it;

import space.arim.jdbcaesar.transact.IsolationLevel;

public enum Vendor {

	HSQLDB,
	
	MARIADB,
	
	POSTGRES,
	
	SQLITE,
	
	H2;
	
	private Vendor() {

	}
	
	/**
	 * Gets how this vendor specifies auto incrementing primary keys, also known as identity
	 * or serial keys.
	 * 
	 * @return how this vendor specifies auto increment keys
	 */
	public String getIdentitySpecification() {
		switch (this) {
		case HSQLDB:
			return "INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY";
		case MARIADB:
			return "INT AUTO_INCREMENT PRIMARY KEY";
		case POSTGRES:
			return "SERIAL PRIMARY KEY";
		case SQLITE:
			return "INTEGER PRIMARY KEY AUTOINCREMENT";
		case H2:
			return "INT IDENTITY NOT NULL PRIMARY KEY";
		default:
			throw new IllegalStateException("I do not know myself");
		}
	}
	
	IsolationLevel defaultIsolation() {
		switch (this) {
		case SQLITE:
			return IsolationLevel.SERIALIZABLE;
		default:
			return IsolationLevel.REPEATABLE_READ;
		}
	}
	
}
